language: minimal

sudo: required

services:
  - docker

script:
  - make build    || travis_terminate 1
  - make test     || travis_terminate 1
  - make release

after_success:
  - bash <(curl -s https://codecov.io/bash)

if: tag IS blank
