version: "3.4"

services:
  app:
    image: "climbcomp/climbcomp-api:${DOCKER_TAG:-latest}"
    build:
      context: "."
      target: "${DOCKER_TARGET:-dev}"
    environment:
      - "CLIMBCOMP_ADDRESS=host.docker.internal:3000"
    ports:
      - "3000:3000"
    volumes:
      - ".:/go/src/app"
