version: "3.4"

services:
  app:
    image: "climbcomp/climbcomp-api:${DOCKER_TAG:-latest}"
    build:
      context: "."
      target: "${DOCKER_TARGET:-dev}"
    ports:
      - "3000:3000"
    volumes:
      - ".:/go/src/app"
