#!/usr/bin/env bash
set -euo pipefail

echo " -> Building"
go build -v -o /usr/local/bin/climbcomp .

echo " -> Installing config and migrations"
mkdir -p /etc/climbcomp
cp -v ./config.yml /etc/climbcomp
cp -vR ./migrations/ /etc/climbcomp

echo " -> Installing bash_completion"
mkdir -p /etc/bash_completion.d
cp ./scripts/autocomplete /etc/bash_completion.d/climbcomp

echo " -> Configuring ~/.bashrc"
BASHRC_LINES=(
    "alias ls='ls -alGh --color=auto'"
    "source /etc/bash_completion.d/climbcomp"
)
for line in "${BASHRC_LINES[@]}"; do
    grep -qxF "${line}" ~/.bashrc || echo "${line}" >> ~/.bashrc
done
